name: photo_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  json_annotation: ^4.8.1
  orm: ^3.4.6
  crypto: ^3.0.3
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.12.1
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
